const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"安排类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryRichanganpai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"消费类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiaofeijilu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"提醒类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhongyaotixing"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"日常安排管理",
                        "menuJump":"列表",
                        "tableName":"richanganpai"
                    }
                ],
                "menu":"日常安排管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"消费记录管理",
                        "menuJump":"列表",
                        "tableName":"xiaofeijilu"
                    }
                ],
                "menu":"消费记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"重要提醒管理",
                        "menuJump":"列表",
                        "tableName":"zhongyaotixing"
                    }
                ],
                "menu":"重要提醒管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"日常安排管理",
                        "menuJump":"列表",
                        "tableName":"richanganpai"
                    }
                ],
                "menu":"日常安排管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"消费记录管理",
                        "menuJump":"列表",
                        "tableName":"xiaofeijilu"
                    }
                ],
                "menu":"消费记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"重要提醒管理",
                        "menuJump":"列表",
                        "tableName":"zhongyaotixing"
                    }
                ],
                "menu":"重要提醒管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
